services:
  postgres:
    image: postgres:18
    container_name: keiverse-postgres
    environment:
      POSTGRES_USER: akuma-w
      POSTGRES_PASSWORD: "22521094"
      POSTGRES_DB: kei_verse_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - kei-verse-network

  redis:
    image: redis:latest
    container_name: keiverse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kei-verse-network
    command: redis-server --appendonly yes

volumes:
  pgdata:
  redis_data:

networks:
  kei-verse-network:
    driver: bridge
    external: true